= Реферат на базу данных

== Название

[Название базы данных]

== Назначение

[Краткое описание назначения базы данных. Например: Хранение и обработка информации о ...]

== Область применения

[Область применения, например: Научные исследования, управление персоналом, финансовый анализ и т.д.]

== Функциональные возможности

[Краткое описание функциональных возможностей. Например: Поиск, сортировка, фильтрация, генерация отчетов, экспорт данных в различных форматах.]

Фильтрация:

* По режиму эксперимента
* По жирным кислотам

Сортировка:

* По времени удерживания
* По разнице времен удерживания
* По эквивалентной длине цепи
* По разнице эквивалентных длин цепей

Форматы экспорта данных:

* IPC - Apache Arrow IPC

== Основные технические характеристики

Язык программирования:: Rust
СУБД:: любая, поддерживающая формат Apache Arrow link:https://arrow.apache.org/docs/format/IPC.html[IPC]

. Таблица измерений:
* Объем: 632 КБ (648_152 байт)
* Количество строк: 3600
* Количество столбцов: 8
* Описание столбцов:
Index::: индекс строки в таблице
Mode::: режим проведения эксперимента (начальная температура, шаг градиента температуры)
FattyAcid::: жирная кислота (количество атомов удлерода, индексы ненасыщенных связей, спецификаторы ненасыщенных связей)
RetentionTime::: время удержания (среднее время удержания, стандартное отклонение времени удержания, относительное время удержания)
Temperature::: температура выхода аналита
ChainLength::: длина цепи (эквивалентная длина цепи, фракционная длина цепи, эквивалентная углеродное число)
Mass::: масса ацилов жирной кислоты ([RCO]+, [RCOO]-, RCOOH, RCOOCH3)
Derivative::: производная функции ECL(RetentionTime)

. Таблица дистанций:
* Объем: 5.65 МБ (5_925_396 байт)
* Количество строк: 63000
* Количество столбцов: 6
* Описание столбцов:
Index::: индекс строки в таблице
Mode::: режим проведения эксперимента (начальная температура, шаг градиента температуры)
From, To::: жирная кислота (количество атомов удлерода, индексы ненасыщенных связей, спецификаторы ненасыщенных связей)
RetentionTime::: дистанция времен удержания от `From` до `To`
ECL::: дистанция эквивалентных длин цепей от `From` до `To`
