angle = Angle
calculate = Calculate
chain_length = Chain length
    .hover = ECL, FCL and ECN
database = Database
delta_degrees_of_freedom = Delta degrees of freedom
    .abbreviation = DDOF
derivative = Derivative
    .hover = Derivative calculations
distance = Distance
equivalent_carbon_number = Equivalent carbon number
    .abbreviation = ECN
equivalent_chain_length = Equivalent chain length
    .abbreviation = ECL
fatty_acid = Fatty acid
    .abbreviation = FA
fatty_acids = Fatty acids
    .hover = Filter by fatty acids
filter = Filter
fractional_chain_length = Fractional chain length
    .abbreviation = FCL
grid = Grid
horizontal = Horizontal
identifier = Identifier
    .abbreviation = ID
    .hover = Measurement identifier
index = Index
language = Language
legend = Legend
logarithmic = Logarithmic
mass = Mass
    .hover = Related masses of [RCO]+, [RCOO]-, RCOOH and RCOOCH3
mode = Mode
    .hover = Measurement mode: onset temperature and temperature step
onset_temperature = Onset temperature
    .hover = Filter by onset temperature
order = Order
    .hover = Order by
order-ascending = Ascending
    .hover = Direct order (from min to max)
order-descending = Descending
    .hover = Reverse order (from max to min)
precision = Precision
relative = Relative
    .hover = Relative fatty acid
reset_gui = Reset GUI
reset_state = Reset state
resize = Resize
retention_time = Retention time
    .hover = Absolute retention time, relative retention time and delta retention time
retention_time-absolute = Absolute
    .hover = Absolute retention time
retention_time-difference = Difference
    .hover = Retention time difference
retention_time-relative = Relative
    .hover = Relative retention time
slope = Slope
sort = Sort
    .hover = Sort by
sort-by_fatty_acid = By fatty acids
    .hover = Sort by fatty acids
sort-by_time = By time
    .hover = Sort by equivalent carbon number and retention time
source = Source
sticky = Sticky
tabs = Tabs
temperature = Temperature
temperature_step = Temperature step
    .hover = Filter by temperature step
truncate = Truncate
vertical = Vertical