alpha = Alpha
    .abbreviation = α
    .hover = ?
absolute-retention-time = Absolute
    .hover = Absolute retention time
angle = Angle
ascending-order = Ascending
    .hover = Direct order (from min to max)
calculate = Calculate
chain-length = Chain length
    .hover = ECL, FCL and ECN
database = Database
delta-degrees-of-freedom = Delta degrees of freedom
    .abbreviation = DDOF
delta-retention-time = Delta
    .hover = Retention time distance to the nearest saturated fatty acid with a lower retention time
derivative = Derivative
    .hover = Derivative calculations
descending-order = Descending
    .hover = Reverse order (from max to min)
distance = Distance
    .hover = Euclidean distance
distance-settings = { -gear } Distance settings
equivalent-carbon-number = Equivalent carbon number
    .abbreviation = ECN
equivalent-chain-length = Equivalent chain length
    .abbreviation = ECL
equivalent-chain-length-distance = Equivalent chain length
    .abbreviation = ΔECL
    .hover = Equivalent chain length distance between two fatty acids
euclidean-distance = Euclidean distance
    .abbreviation = d
    .hover = Euclidean distance (in coordinates retention time and equivalent chain length) between two fatty acids
fatty-acid = Fatty acid
    .abbreviation = FA
filter = Filter
filter-by-fatty-acids = Fatty acids
    .hover = Filter by fatty acids
filter-by-onset-temperature = Onset temperature
    .hover = Filter by onset temperature
filter-by-temperature-step = Temperature step
    .hover = Filter by temperature step
fractional-chain-length = Fractional chain length
    .abbreviation = FCL
from = From
grid = Grid
horizontal = Horizontal
identifier = Identifier
    .abbreviation = ID
    .hover = Measurement identifier
index = Index
language = Language
legend = Legend
logarithm-of-the-retention-time = Logarithmic
    .hover = Calculate the equivalent chain length using the logarithms of the retention times
mass = Mass
    .hover = Related masses of [RCO]+, [RCOO]-, RCOOH and RCOOCH3
mode = Mode
    .hover = Measurement mode: onset temperature and temperature step
onset-temperature = Onset temperature
    .abbreviation = T₀
order = Order
    .hover = Order by
precision = Precision
radius-of-points = Radius of points
    .hover = The radius of all points on the plot
relative-fatty-acid = Relative
    .hover = The fatty acid to calculate relative retention time
relative-retention-time = Relative
    .hover = Relative retention time calculated through the selected fatty acid
reset-gui = Reset GUI
reset-state = Reset state
resize = Resize
retention-time = Retention time
    .abbreviation = RT
    .hover = Retention time (absolute, relative and distance)
retention-time-distance = Retention time
    .abbreviation = ΔRT
    .hover = Retention time distance between two fatty acids
slope = Slope
sort-by = Sort
    .hover = Sort by
sort-by-distance = Sort
    .hover = Sort by distance
sort-by-alpha = Alpha
    .hover = Sort by alpha distance
sort-by-equivalent-chain-length-distance = Equivalent chain length
    .hover = Sort by equivalent chain length distance
sort-by-euclidean-distance = Euclidean
    .hover = Sort by euclidean distance
sort-by-fatty-acids = Fatty acids
    .hover = Sort by fatty acids
sort-by-retention-time = Retention time
    .hover = Sort by equivalent carbon number and retention time
sort-by-retention-time-distance = Retention time
    .hover = Sort by retention time distance
source = Source
source-settings = { -gear } Source settings
sticky = Sticky
tabs = Tabs
temperature = Temperature
    .abbreviation = T
    .hover = Eluating temperature
temperature-step = Temperature step
    .abbreviation = ΔT
    .hover = Temperature increment per minute
to = To
truncate = Truncate
    .hover = Truncate table headers
vertical = Vertical

sort-by-key = Key
    .hover = Sort by key
sort-by-value = Value
    .hover = Sort by value
sort-by-aggregation = Aggregation
    .hover = Use some aggregation function to calculate the value to sort
sort-by-maximum = Maximum
    .hover = Select the maximum of the values to sort
sort-by-median = Median
    .hover = Select the median of the values to sort
sort-by-minimum = Minimum
    .hover = Select the minimum of the values to sort
