angle = Angle
calculate = Calculate
chain_length = Chain length
    .hover = ECL, FCL and ECN
database = Database
delta_degrees_of_freedom = Delta degrees of freedom
    .abbreviation = DDOF
derivative = Derivative
    .hover = Derivative calculations
distance = Distance
equivalent_carbon_number = Equivalent carbon number
    .abbreviation = ECN
equivalent_chain_length = Equivalent chain length
    .abbreviation = ECL
fatty_acid = Fatty acid
    .abbreviation = FA
filter = Filter
fractional_chain_length = Fractional chain length
    .abbreviation = FCL
grid = Grid
horizontal = Horizontal
identifier = Identifier
    .abbreviation = ID
    .hover = Measurement identifier
index = Index
language = Language
legend = Legend
logarithmic = Logarithmic
mass = Mass
    .hover = Related masses of [RCO]+, [RCOO]-, RCOOH and RCOOCH3
mode = Mode
    .hover = Measurement mode: onset temperature and temperature step
order = Order
    .hover = Order by
ascending-order = Ascending
    .hover = Direct order (from min to max)
descending-order = Descending
    .hover = Reverse order (from max to min)
precision = Precision
relative = Relative
    .hover = Relative fatty acid
reset_gui = Reset GUI
reset_state = Reset state
resize = Resize
retention_time = Retention time
    .hover = Absolute retention time, relative retention time and delta retention time
retention_time-absolute = Absolute
    .hover = Absolute retention time
retention_time-difference = Difference
    .hover = Retention time difference
retention_time-relative = Relative
    .hover = Relative retention time
slope = Slope
sort = Sort
    .hover = Sort by
sort-by_fatty_acid = By fatty acids
    .hover = Sort by fatty acids
sort-by_time = By time
    .hover = Sort by equivalent carbon number and retention time
source = Source
sticky = Sticky
tabs = Tabs
temperature = Temperature
    .hover = Eluating temperature
truncate = Truncate
vertical = Vertical

distance = Distance
    .hover = Euclidean distance
euclidean_distance = Euclidean
    .hover = Euclidean distance

sort-by-distance = Sort
    .hover = Sort by distance

sort-by-equivalent-chain-length-distance = Equivalent chain length
    .hover = Sort by equivalent chain length distance
sort-by-euclidean-distance = Euclidean
    .hover = Sort by euclidean distance
sort-by-retention-time-distance = Retention time
    .hover = Sort by retention time distance
filter-by-onset-temperature = Onset temperature
    .hover = Filter by onset temperature
filter-by-temperature-step = Temperature step
    .hover = Filter by temperature step
filter-by-fatty-acids = Fatty acids
    .hover = Filter by fatty acids

from = From
to = To
mode-temperature_step = Step
    .hover = Temperature step
mode-onset_temperature = Onset
    .hover = Onset temperature